name: CI

on:
    push:
    pull_request:

jobs:
    build:
        name: Docker build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Pull images
              run: docker-compose pull
            - name: Start services
              run: docker-compose up --build -d
            - name: Wait for services
              run: sleep 15
            - name: check syntax
              run: docker-compose exec -T symfony vendor/bin/php-cs-fixer fix src --diff --dry-run -v --allow-risky=yes
            - name: Check HTTP reachability
              run: curl http://localhost
            - name: Check HTTPS reachability
              run: curl -k https://localhost
